version: '3.8'
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: always
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=windkingMeiliKey

  weaviate:
    image: semitechnologies/weaviate:1.24.10
    container_name: weaviate
    restart: always
    ports:
      - "8080:8080"     # REST API
      - "50051:50051"   # gRPC
    volumes:
      - ./weaviate_data:/var/lib/weaviate
      - ./weaviate_logs:/var/log/weaviate
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-openai
      - OPENAI_APIKEY=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
      - ENABLE_MODULES=text2vec-openai

